# ==========================================================
# Gradle
# ==========================================================

org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

# ==========================================================
# Minecraft / Forge
# ==========================================================

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)

forge_version=47.4.23
forge_version_range=[47,)

loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

# ==========================================================
# Mod
# ==========================================================

mod_id=tacticalbackpack
mod_name=TacticalBackpack

mod_version=v0.1.0

mod_group_id=com.github.kisaragimikoto

mod_license=All Rights Reserved

mod_authors=Kisaragi Mikoto

mod_description=Multi integration backpack supporting Cobblemon, Curios, TacZ, Epic Fight, Mekanism, Create, SlashBlade, L2, Farmer's Delight, CC:Tweaked and more.